# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "micropython-esp32-stubs" = super.buildPythonPackage rec {
    pname = "micropython-esp32-stubs";
    version = "1.26.0.post1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/f7/d44a28971ed7c21de417b31a056c44e3cae34c0bd4bd5da7aa2d1381cc85/micropython_esp32_stubs-1.26.0.post1-py2.py3-none-any.whl";
      sha256 = "0a9hsh839nyi7l1nmdmx2sva2iljln32s1mhzk2jfiqyf7a4j0wk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."micropython-stdlib-stubs"
    ];
  };
  "micropython-stdlib-stubs" = super.buildPythonPackage rec {
    pname = "micropython-stdlib-stubs";
    version = "1.26.0.post3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4f/2e/38a03713acf949c571e54de7c64fb48a519521c4ff0c1645d5213316637e/micropython_stdlib_stubs-1.26.0.post3-py3-none-any.whl";
      sha256 = "179kg2i8r847di1midrx34r7q4cav788v61q1md61jpymwgmm8wq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
